version: '3'

services:
  web:
    image: nginx:1.12
    ports:
      - "80:80"
    volumes:
      - ./php/:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./php/
      args:
        arg: 1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

